version: "2.1"

orbs:
  shellcheck: circleci/shellcheck@3.2.0
  semantic-release: trustedshops-public/semantic-release@6.0.0

jobs:
  semantic-release:
    executor: semantic-release/default
    steps:
      - checkout
      - setup_remote_docker
      - semantic-release/install:
          additional_packages: '@semantic-release/exec'
      - run:
          name: Install os dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y gettext uuid-runtime
      - semantic-release/execute
  upload-release-to-gh-pages:
    executor: semantic-release/default
    steps:
      - checkout
      - run:
          name: Upload release to pages
          command: ./upload-release-to-pages.sh "${CIRCLE_TAG}"

workflows:
  main:
    jobs:
      - shellcheck/check:
          name: shellcheck
          dir: src
      - semantic-release:
          requires:
            - shellcheck
      - upload-release-to-gh-pages:
          filters:
            tags:
              only: /^test.*/
            branches:
              ignore: /.*/
